name: Dr. Matthew Thomas
email: matthewllthomas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My landing page for whatever I do
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman